# Generated by Django 5.0.3 on 2024-04-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_report_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='classification',
            new_name='bothclassification',
        ),
        migrations.AddField(
            model_name='report',
            name='leftclassification',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='rightclassification',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
