# Generated by Django 5.0.3 on 2024-04-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='attachment',
            new_name='image',
        ),
    ]
