# Generated by Django 5.0.3 on 2024-04-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.TextField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default='N/A'),
        ),
    ]
