# Generated by Django 5.0.6 on 2024-05-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_documentfolderpath_destin_path_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Struct',
        ),
    ]
