# Generated by Django 5.0.6 on 2024-05-09 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_struct'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='radiologists',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
