# Generated by Django 5.0.6 on 2024-06-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_report_acr_alter_report_bothe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='acr',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='bothE',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='bothM',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='bothclassification',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='conclusion',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='indication',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='leftE',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='leftM',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='leftclassification',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='noneE',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='noneM',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='recommendations',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='rightE',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='rightM',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='rightclassification',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
    ]
